DiMissionFileParser/DiMissionFileParser.Web/Models/ErrorViewModel.cs
namespace DiMissionFileParser.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DiMissionFileParser/DiMissionFileParser.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DiMissionFileParser.Web.Models;

namespace DiMissionFileParser.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DiMissionFileParser/DiMissionFileParser.Web/Controllers/MissionTextController.cs
using System;
using System.IO;
using System.Linq;
using DiMissionfileParser.Parser.Functions;
using DiMissionfileParser.Parser.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiMissionFileParser.Web.Controllers
{
    public class MissionTextController : Controller
    {
        private readonly MissionTextDataContext _context;

        public MissionTextController()
        {
            var dataDir = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            var path = Path.Combine(dataDir, "apache_texts\\texts");
            _context = new MissionTextDataContext(path);
        }


        // GET: MissionText
        public ActionResult Index()
        {
            return View(_context.MissionTexts);
        }

        // GET: MissionText/Details/5
        public ActionResult Details(string id)
        {
            var file = _context.MissionTexts.Single(s => s.FileName == id);
            return GetDetailsView(file);
        }

        private ViewResult GetDetailsView(MissionText file)
        {
            return View(file.GetType().Name, file);
        }
    }
}

DiMissionFileParser/DiMissionFileParser.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DiMissionFileParser/DiMissionFileParser.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DiMissionFileParser/DiMissionFileParser.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DiMissionFileParser/DiMissionFileParser.Web/Views/MissionText/Index.cshtml
@model System.Collections.Generic.List<DiMissionfileParser.Parser.Models.MissionText>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Mission files</h2>
<table>
    <tr>
        <th>File name</th>
        <th>String representation</th>
    </tr>
    @foreach (var file in Model)
    {
        <tr>
            <td>@file.FileName</td>
            <td>@Html.ActionLink(file.ToString(), "Details", new { id = file.FileName })</td>
        </tr>
    }
</table>

DiMissionFileParser/DiMissionFileParser.Web/Views/MissionText/MissionTextCampaign.cshtml
@model DiMissionfileParser.Parser.Models.MissionTextCampaign

@{
    ViewData["Title"] = "MissionTextCampaign";
}

<h2>MissionTextCampaign</h2>

<div>
    <h4>Campaign @Model.FileName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dd>
            @foreach (var text in Model.Situations)
            {
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => text.Situation)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => text.Situation)
                    </dd>
                </dl>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Successful)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Successful)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Failure)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Failure)
        </dd>
    </dl>
</div>

DiMissionFileParser/DiMissionFileParser.Web/Views/MissionText/MissionTextSituation.cshtml
@model DiMissionfileParser.Parser.Models.MissionTextSituation

@{
    ViewData["Title"] = "MissionTextSituation";
}

<h2>MissionTextSituation</h2>

<div>
    <h4> @Html.DisplayFor(model => model.FileName)</h4>
    <hr />
    
</div>

DiMissionFileParser/DiMissionFileParser.Web/Views/MissionText/MissionTextTitled.cshtml
@model DiMissionfileParser.Parser.Models.MissionTextTitled

@{
    ViewData["Title"] = "MissionTextTitled";
}

<h2>MissionTextTitled</h2>

<div>
    <h4>            @Html.DisplayFor(model => model.FileName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Para)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Para)
        </dd>
    </dl>
</div>

DiMissionFileParser/DiMissionFileParser.Web/Views/MissionText/MissionTextWithResult.cshtml
@model DiMissionfileParser.Parser.Models.MissionTextWithResult

@{
    ViewData["Title"] = "MissionTextWithResult";
}

<h2>MissionTextWithResult</h2>

<div>
    <h4>            @Html.DisplayFor(model => model.FileName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Para)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Para)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Outstanding)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Outstanding)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Success)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Success)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Failue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Failue)
        </dd>
    </dl>
</div>

DiMissionFileParser/DiMissionFileParser.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiMissionFileParser.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DiMissionFileParser.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="MissionText" asp-action="Index">Mission Texts</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DiMissionFileParser.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>